### YamlMime:ContributionMeta
---
uid: "contribution/preset-manager-meta"
type: "tool"
author: "joao"
date: "26 Feb, 2019"
title: "Preset Manager"
originalURL: "contribution/preset-manager"
category: "tool"
like_count: "2"
imported: "true"
teaser: |-
  **Preset Manager for vvvv**
  
  Preset Manager is an easy and fast tool for saving predefined settings in your vvvv patch. It makes use of the node expose functionality in vvvv to save and load values to and from a .xml file.
  
  
  
  **Usage**
  
  1 - Select and press "CTRL+K" to expose an IOBox to the Preset Manager (Exposed IOBoxes will turn green)
  
  2 - To Save a new preset: Select the Path in "Save As" and hit "Save New"
  
  3 - "Save" will save to the current preset.
  
  
  
  **Supported Types**
  
  	- IOBox (value Spread)
  	- IOBox (color Spread)
  	- IOBox (String Spread)
  
  
  **Working Repository**
  
  <https://github.com/joaodafonseca/VVVV-PresetManager>
  
  
  
  **Credits**
  
  Thanks to Lasal for the VL optimization support.
