### YamlMime:ContributionMeta
---
uid: "contribution/svvvvitcher-meta"
type: "tool"
author: "tonfilm"
date: "13 Jun, 2010"
title: "Svvvvitcher"
originalURL: "contribution/svvvvitcher"
category: "tool"
credits: |-
  big thanks to [west](http://vvvv.org/users/west%22+%22west), [colorsound](http://vvvv.org/users/colorsound%22+%22colorsound), [elektromeier](http://vvvv.org/users/elektromeier%22+%22elektromeier), [joreg](http://vvvv.org/users/joreg%22+%22joreg) and [linedot](http://www.myspace.com/strichpunktton) for beta testing and adding ideas.
like_count: "29"
imported: "true"
teaser: |-
  ## why?
  
  after three attempts to make a nice vj tool, i came to the conclusion, that the most powerful thing is to switch patches. because a patch can do just anything, it can contain videos, pictures, 3d models, generative stuff etc.. and... there are just thousands around. every vvvv patcher has lots of try outs, small ideas and whatever on his harddrive. wouldn't it just nice to drop them all into a folder and mix them on a vj set? sure it is!
